// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsmrvctjezodqhwpxegz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzbXJ2Y3RqZXpvZHFod3B4ZWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODQ2NzcsImV4cCI6MjA1Njc2MDY3N30.9CYdX93jh5gAP7O91Ot6g7NhlQdWh0JxrgKiau_d1r0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);